import json
import math
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from route_analysis import scenario_geometry
from route_analysis.clearance_geometry import corner_radii
from route_analysis.models import ClearanceStatus, VehicleDimensions
from route_analysis.scenario_geometry import (
    CENTRED,
    NO_PINS,
    SOLVED_KEYS,
    Condition,
    Gear,
    Offsets,
    Pins,
    RoadDimensions,
    Scenario,
    ScenarioInputs,
    build_layout,
    offset_rows,
)
from route_analysis.scenario_solver import (
    COARSE,
    FINE,
    Steps,
    evaluate,
    evaluate_layout,
    feasible_bands,
    offset_specs,
    optimise_offsets,
    sample_poses,
    solve_forward,
    solve_scenario,
)

DIMENSIONS = VehicleDimensions(width=1.23, center_front=1.545, center_rear=2.223)
FIXTURE = Path(__file__).parent / "fixtures" / "scenario_clearance.json"

DIMENSION_KEYS = {
    "wA": "wa", "wB": "wb", "wV": "wv", "wH": "wh",
    "LS": "ls", "w": "w", "b": "b", "D": "d",
}
OFFSET_KEYS = {
    "eA": "ea", "eB": "eb", "eV": "ev", "eH": "eh", "a": "a",
    "so": "so", "e1": "e1", "e2": "e2", "eo": "eo", "yc": "yc",
}
PROTOTYPE_END_WALL = 0.15
"""What the prototype reports when its artificial end wall binds: a fixed 0.15 m trim."""

PROTOTYPE_INDEPENDENCE = """夹具的独立性对场景而言并不一致，这一点值得写明。

原型是设计交付稿先写的，Python 由它移植而来，所以两边一致证明的是移植忠实。借支路
与双向 U 型两个场景后来按需求方的确认改了机动，原型随之同步 —— 那两处的机动形状因此
不再是独立佐证，等于同一份理解写了两遍。

仍然独立的部分是求值链路本身：原型自己算线段间距与点在多边形内，Python 走 shapely 的
向量化接口，两条完全不同的路。区域构造、位姿采样、镜像与净距计算对全部四个场景依旧
是真正的交叉验证。
"""


def _inputs(**overrides) -> ScenarioInputs:
    base = {"dimensions": DIMENSIONS, "radius": 1.60, "threshold": 0.05}
    return ScenarioInputs(**(base | overrides))


def _pareto(**overrides) -> ScenarioInputs:
    return _inputs(condition=Condition.PARETO, **overrides)


def _fixture_cases():
    data = json.loads(FIXTURE.read_text())
    return data["vehicle"], data["cases"]


def _fixture_inputs(case, dimensions: VehicleDimensions, radius: float) -> ScenarioInputs:
    return _inputs(
        scenario=Scenario(case["type"]),
        bidirectional=case["bidir"],
        gear=Gear(case["gear"]),
        dimensions=dimensions,
        radius=radius,
    )


def _fixture_dims(case) -> RoadDimensions:
    return RoadDimensions(
        **{DIMENSION_KEYS[key]: value for key, value in case["dims"].items()}
    )


def _fixture_offsets(case) -> Offsets:
    """The prototype's offsets in the Python sign convention.

    The stub branch offset ``so`` is positive towards the inside of the turn now, like every
    other offset; the prototype that generated the fixture still uses the old sign and has
    not been resynced, so its ``so`` is negated on the way in. The fixture itself is left
    exactly as the prototype wrote it.
    """

    values = {OFFSET_KEYS[key]: value for key, value in case["off"].items()}
    values["so"] = -values["so"]
    return Offsets(**values)


def test_geometry_layer_matches_the_prototype_case_for_case(monkeypatch):
    """Case-for-case cross-check against the prototype: region, path, sampling, mirror, gear.

    With the end-wall padding at zero the region matches the prototype exactly, so every
    case has to agree to the last digit. The padding itself is covered separately by
    ``test_padded_end_walls_only_ever_loosen_the_result``.

    The fixture was generated by the prototype before the stub branch offset ``so`` had its
    sign flipped to "positive towards the inside", so ``_fixture_offsets`` negates it.
    """

    monkeypatch.setattr(scenario_geometry, "CAP_PAD", 0.0)
    vehicle, cases = _fixture_cases()
    dimensions = VehicleDimensions(
        width=vehicle["W"], center_front=vehicle["Lf"], center_rear=vehicle["Lr"]
    )
    compared = 0
    for case in cases:
        inputs = _fixture_inputs(case, dimensions, vehicle["R"])
        steps = Steps(case["arc_step"], case["line_step"])
        actual = evaluate(
            inputs, _fixture_dims(case), _fixture_offsets(case), steps, detail=True
        ).clearance
        assert actual == pytest.approx(case["clearance"], abs=1e-6), case
        compared += 1
    assert compared > 200, "对拍用例太少，夹具可能没重新生成"


def test_padded_end_walls_only_ever_loosen_the_result():
    """Padding the end walls removes a constraint, so clearance can only grow.

    Same sign caveat as the case-for-case check: the prototype's ``so`` is negated on load.
    """

    vehicle, cases = _fixture_cases()
    dimensions = VehicleDimensions(
        width=vehicle["W"], center_front=vehicle["Lf"], center_rear=vehicle["Lr"]
    )
    loosened = 0
    for case in cases:
        inputs = _fixture_inputs(case, dimensions, vehicle["R"])
        actual = evaluate(
            inputs,
            _fixture_dims(case),
            _fixture_offsets(case),
            Steps(case["arc_step"], case["line_step"]),
            detail=True,
        ).clearance
        assert actual >= case["clearance"] - 1e-6, case
        if actual > case["clearance"] + 1e-6:
            loosened += 1
    assert loosened, "没有任何用例被端墙顶住，夹具已经失去回归价值"


def test_the_prototype_end_wall_capped_every_roomy_case():
    """Record what was fixed: give the prototype room and its clearance pins to the trim."""

    _, cases = _fixture_cases()
    capped = [
        case
        for case in cases
        if math.isclose(case["clearance"], PROTOTYPE_END_WALL, abs_tol=1e-9)
    ]
    assert len(capped) > 50


def test_four_corner_radii_come_from_the_closed_form():
    inputs = _pareto(scenario=Scenario.CORNER)
    result = solve_scenario(inputs, RoadDimensions(), pins=Pins.all_dims(Scenario.CORNER))
    assert result.corner_radii == corner_radii(DIMENSIONS, inputs.radius)


@pytest.mark.parametrize("scenario", list(Scenario))
def test_the_two_mirrored_maneuvers_are_equally_tight(scenario):
    """A two-way layout is symmetric, so both mirrored maneuvers are equally tight."""

    inputs = _inputs(scenario=scenario, bidirectional=True)
    layout = build_layout(inputs, RoadDimensions(), Offsets())
    values = [
        evaluate_layout(
            replace(layout, maneuvers=(maneuver,)), DIMENSIONS, FINE
        ).clearance
        for maneuver in layout.maneuvers
    ]
    assert values[0] == pytest.approx(values[1], abs=1e-9)


def test_gear_swaps_which_leg_needs_the_extra_width():
    """D eats the rear outer corner and R the front outer, swapping what each leg needs."""

    drive = solve_scenario(
        _inputs(scenario=Scenario.CORNER, gear=Gear.DRIVE), RoadDimensions()
    )
    reverse = solve_scenario(
        _inputs(scenario=Scenario.CORNER, gear=Gear.REVERSE), RoadDimensions()
    )
    assert drive.dims.wa == pytest.approx(reverse.dims.wb, abs=2e-3)
    assert drive.dims.wb == pytest.approx(reverse.dims.wa, abs=2e-3)


@pytest.mark.parametrize(
    ("scenario", "bidirectional", "condition"),
    [
        (Scenario.CORNER, False, Condition.CENTRELINE),
        (Scenario.CORNER, True, Condition.PARETO),
        (Scenario.CROSSBACK, False, Condition.CENTRELINE),
        (Scenario.STUBBACK, False, Condition.CENTRELINE),
        (Scenario.UTURN, False, Condition.CENTRELINE),
        (Scenario.UTURN, True, Condition.PARETO),
    ],
)
def test_solved_dimensions_fed_back_in_still_clear_the_threshold(
    scenario, bidirectional, condition
):
    """The headline check: feed a solved road back in and it must still clear the threshold.

    The road and the offsets it was solved with go straight back into the clearance engine.
    Under the Pareto condition the same road is also fed back through ``solve_scenario``
    with every dimension pinned, which is the pure check the operator gets, and its verdict
    has to be a pass.
    """

    inputs = _inputs(scenario=scenario, bidirectional=bidirectional, condition=condition)
    solved = solve_scenario(inputs, RoadDimensions())
    assert not solved.infeasible
    rechecked = evaluate(inputs, solved.dims, solved.offsets, FINE, detail=True)
    assert rechecked.clearance >= inputs.threshold - 1e-6
    if inputs.pareto:
        checked = solve_scenario(inputs, solved.dims, pins=Pins.all_dims(scenario))
        assert checked.solved_keys == ()
        assert checked.min_clearance >= inputs.threshold - 1e-6
        assert checked.status is ClearanceStatus.SAFE


@pytest.mark.parametrize("scenario", list(Scenario))
def test_a_bigger_threshold_never_asks_for_a_smaller_road(scenario):
    previous = None
    for threshold in (0.05, 0.15, 0.30):
        result = solve_scenario(
            _inputs(scenario=scenario, threshold=threshold), RoadDimensions()
        )
        assert not result.infeasible, (scenario, threshold)
        current = [getattr(result.dims, key) for key in SOLVED_KEYS[scenario]]
        if previous is not None:
            assert sum(current) >= sum(previous) - 1e-6
        previous = current


def test_a_generous_threshold_is_still_solvable():
    """Regression: with end walls in the measurement, any threshold above the path trim

    made every scenario permanently infeasible.
    """

    result = solve_scenario(
        _inputs(scenario=Scenario.CORNER, threshold=0.30), RoadDimensions()
    )
    assert not result.infeasible
    assert result.min_clearance == pytest.approx(0.30, abs=5e-3)


def test_widening_the_road_never_tightens_the_clearance():
    inputs = _inputs(scenario=Scenario.CORNER)
    previous = None
    for width in (2.6, 3.0, 3.6, 4.4):
        clearance = evaluate(
            inputs, RoadDimensions(wa=width, wb=width), CENTRED, FINE, detail=True
        ).clearance
        if previous is not None:
            assert clearance >= previous - 1e-9
        previous = clearance


def test_the_two_way_uturn_leaves_the_middle_aisle_and_returns_to_an_outer_one():
    """Both maneuvers set off up the shared middle aisle and come back down opposite outers.

    They used to run it the other way -- up an outer, down the middle -- which put the two of
    them finishing nose to nose in the aisle they share. Same circle either way; what changes
    is which way round it is driven, and in D gear that decides whether the rear outer corner
    swings at the outer wall or out into the open turning head.
    """

    result = solve_scenario(
        _inputs(scenario=Scenario.UTURN, bidirectional=True), RoadDimensions()
    )
    pitch = result.dims.w + result.dims.b
    finishes = []
    for maneuver in result.layout.maneuvers:
        samples = sample_poses(maneuver.primitives, DIMENSIONS, FINE)
        assert samples.x[0] == pytest.approx(0.0, abs=1e-6), "起点必须在中巷"
        finishes.append(float(samples.x[-1]))
    assert len(finishes) == 2
    assert sorted(finishes) == pytest.approx([-pitch, pitch], abs=2e-3)


def test_the_two_way_uturn_pins_the_shared_middle_aisle():
    """Only the outer aisles may be offset; the middle one is driven by both maneuvers.

    Offsetting it would move it one way for one maneuver and the other way for its mirror.
    """

    inputs = _pareto(scenario=Scenario.UTURN, bidirectional=True)
    keys = {spec.key for spec in offset_specs(inputs, RoadDimensions())}
    assert "eo" in keys
    assert not {"e1", "e2"} & keys


@pytest.mark.parametrize("bidirectional", [False, True])
@pytest.mark.parametrize("scenario", list(Scenario))
def test_the_free_offsets_are_exactly_the_unshared_rows(scenario, bidirectional):
    """The sidebar's rows and the optimiser's variables must be the same list."""

    inputs = _pareto(scenario=scenario, bidirectional=bidirectional)
    free = {spec.key for spec in offset_specs(inputs, RoadDimensions())}
    listed = {
        row.key
        for row in offset_rows(scenario, bidirectional=bidirectional)
        if not row.shared
    }
    assert free == listed


def test_a_pinned_offset_drops_out_of_the_free_variables():
    inputs = _pareto(scenario=Scenario.CORNER)
    pins = Pins(offsets=frozenset({"ea"}))
    assert {spec.key for spec in offset_specs(inputs, RoadDimensions(), pins)} == {"eb"}
    assert {spec.key for spec in offset_specs(inputs, RoadDimensions())} == {"ea", "eb"}


def test_uturn_that_cannot_hold_the_radius_says_how_wide_it_must_be():
    """A pure check of the given aisles: both lateral offsets pinned at zero as well.

    Left free, the optimiser leans both aisles outwards to widen the circle and reports a
    smaller shortfall than the road as drawn has.
    """

    check = Pins.all_dims(Scenario.UTURN).with_offset("e1", True).with_offset("e2", True)
    result = solve_scenario(
        _pareto(scenario=Scenario.UTURN), RoadDimensions(w=1.8, b=0.6), pins=check
    )
    assert result.infeasible
    assert result.radius_shortfall == pytest.approx(0.4)
    assert result.required_lane_width == pytest.approx(2.6)


def test_an_impossible_threshold_reports_the_ceiling_it_could_reach():
    result = solve_scenario(
        _inputs(scenario=Scenario.CORNER, threshold=8.0), RoadDimensions()
    )
    assert result.infeasible
    assert result.threshold_ceiling is not None
    assert 0.0 <= result.threshold_ceiling < 8.0


def test_status_follows_the_same_rule_as_the_overrun_analysis():
    """Pin the dimensions and both lateral offsets: a pure check on the centreline road."""

    check = Pins.all_dims(Scenario.CORNER).with_offset("ea", True).with_offset("eb", True)
    tight = solve_scenario(
        _pareto(scenario=Scenario.CORNER), RoadDimensions(wa=3.0, wb=3.0), pins=check
    )
    assert tight.offsets == CENTRED
    assert tight.min_clearance < 0
    assert tight.status is ClearanceStatus.OUTSIDE
    marginal = solve_scenario(
        _pareto(scenario=Scenario.CORNER, threshold=0.6),
        RoadDimensions(wa=4.2, wb=4.2),
        pins=check,
    )
    assert 0 <= marginal.min_clearance < 0.6
    assert marginal.status is ClearanceStatus.WARNING


def test_the_offsets_the_optimiser_returns_stay_inside_their_own_bounds():
    inputs = _pareto(scenario=Scenario.CORNER)
    dims = RoadDimensions()
    offsets, _ = optimise_offsets(inputs, dims, COARSE, cheap=True)
    for spec in offset_specs(inputs, dims):
        assert spec.low - 1e-9 <= getattr(offsets, spec.key) <= spec.high + 1e-9


@pytest.mark.parametrize(
    ("scenario", "dims"),
    [
        (Scenario.CORNER, RoadDimensions(wa=3.6, wb=3.6)),
        (Scenario.CORNER, RoadDimensions(wa=3.0, wb=3.0)),
        (Scenario.STUBBACK, RoadDimensions()),
        (Scenario.CROSSBACK, RoadDimensions()),
        (Scenario.UTURN, RoadDimensions()),
    ],
)
def test_feasible_bands_always_contain_the_offset_they_report(scenario, dims):
    """The reported offset has to sit inside its own band or two rows contradict."""

    result = solve_scenario(_pareto(scenario=scenario), dims, pins=Pins.all_dims(scenario))
    assert result.bands
    for band in result.bands:
        assert not band.empty, band
        chosen = getattr(result.offsets, band.key)
        assert band.low <= chosen <= band.high, (band, chosen)


@pytest.mark.parametrize("scenario", [Scenario.CORNER, Scenario.UTURN])
def test_centred_comparison_matches_the_centreline_variant(scenario):
    """The comparison row must land on the same number the centreline variant reports.

    The centreline condition ignores pins, so "centreline, everything pinned" is the solved
    centreline road; checking that road under the Pareto condition with every dimension
    pinned has to report it as the centred clearance to the last digit.
    """

    centre = solve_scenario(
        _inputs(scenario=scenario), RoadDimensions(), pins=Pins.all_dims(scenario)
    )
    assert centre.solved_keys == SOLVED_KEYS[scenario], "中心线条件下固定项被忽略"
    pareto = solve_scenario(
        _pareto(scenario=scenario), centre.dims, pins=Pins.all_dims(scenario)
    )
    assert pareto.solved_keys == ()
    assert pareto.centred_clearance == pytest.approx(centre.min_clearance, abs=1e-9)


def test_pose_sampling_puts_the_body_where_the_gear_says():
    inputs = _inputs(scenario=Scenario.CORNER, gear=Gear.DRIVE)
    layout = build_layout(inputs, RoadDimensions(), Offsets())
    samples = sample_poses(layout.maneuvers[0].primitives, DIMENSIONS, FINE)
    assert len(samples) > 100
    lead = samples.corners[0][0]
    assert lead[0] == pytest.approx(samples.x[0] + DIMENSIONS.center_front, abs=1e-9)


def test_forward_solution_reports_the_ceiling_even_when_it_succeeds():
    solution = solve_forward(_inputs(scenario=Scenario.CORNER), RoadDimensions())
    assert solution.dims is not None
    assert solution.ceiling_clearance > 0.05


def _search_ceilings(inputs: ScenarioInputs, given: RoadDimensions) -> dict[str, float]:
    """The upper end of each solved dimension's bracket, mirroring ``solve_forward``."""

    vehicle = inputs.dimensions
    width_high = (
        vehicle.width
        + 2 * inputs.threshold
        + 2 * max(math.hypot(inputs.radius + vehicle.width / 2, vehicle.center_rear)
                  - inputs.radius, inputs.radius)
        + 2.4
    )
    lane_seed = max(vehicle.width + 2 * inputs.threshold, 2 * inputs.radius - given.b) + 1
    return {
        "wa": width_high, "wb": width_high, "wv": width_high, "wh": width_high,
        "ls": inputs.radius + vehicle.center_rear + inputs.threshold + 1.8,
        "w": width_high + 2 * inputs.radius,
        "d": inputs.radius + lane_seed + vehicle.center_rear + inputs.threshold + 3,
    }


@pytest.mark.parametrize("bidirectional", [False, True])
@pytest.mark.parametrize("condition", list(Condition))
@pytest.mark.parametrize("scenario", list(Scenario))
def test_no_solved_dimension_is_left_at_its_search_ceiling(
    scenario, condition, bidirectional
):
    """A dimension stuck at the top of its bracket means the search found nothing, not

    that the road really has to be that wide. Two-way crossback used to report a 7.02 m
    turn-out road -- past its own 6.93 m ceiling, rescued there by the guard bump -- and
    the view presented it as solved.
    """

    inputs = _inputs(scenario=scenario, bidirectional=bidirectional, condition=condition)
    given = RoadDimensions()
    result = solve_scenario(inputs, given)
    assert not result.infeasible
    ceilings = _search_ceilings(inputs, given)
    for key in SOLVED_KEYS[scenario]:
        assert getattr(result.dims, key) < ceilings[key] - 1e-6, (key, result.dims)


def test_two_way_crossback_does_not_trade_the_whole_road_for_the_dip():
    """Regression: compressing one dimension at a time let whichever went first take the

    entire budget while the rest still sat at their ceilings, so the two-way turn-out road
    solved to 7.02 m beside a 0.36 m dip when the one-way answer -- 2.31 m and 2.72 m --
    fits the two-way layout too. Its region is the one-way one minus a wall and its second
    maneuver is an exact mirror, so two-way can never need a wider road than one-way here.
    """

    one_way, two_way = (
        solve_scenario(
            _inputs(scenario=Scenario.CROSSBACK, bidirectional=bidirectional),
            RoadDimensions(),
        ).dims
        for bidirectional in (False, True)
    )
    assert two_way.wh == pytest.approx(one_way.wh, abs=2e-3)
    assert two_way.ls == pytest.approx(one_way.ls, abs=2e-3)
    assert two_way.wv == pytest.approx(one_way.wv, abs=2e-3)


@pytest.mark.parametrize("bidirectional", [False, True])
@pytest.mark.parametrize("scenario", list(Scenario))
def test_letting_the_truck_leave_the_centreline_never_widens_the_road(
    scenario, bidirectional
):
    """The Pareto condition only adds freedom, so no dimension may come out larger.

    Every offset is free to stay at zero, which makes the centreline road feasible under
    the Pareto condition too. Reporting a wider one says permission to leave the
    centreline forced a bigger road, which nobody can act on. Ten of the twelve variants
    used to do it -- two-way crossback asked 4.46 m of turn-out road against 2.51 m --
    because the offset optimiser takes a large offset early, while the road is still wide
    enough to make it free, and whichever dimension has to contain that offset is then
    stuck holding it.
    """

    solved = {}
    for condition in Condition:
        inputs = _inputs(
            scenario=scenario, bidirectional=bidirectional, condition=condition
        )
        result = solve_scenario(inputs, RoadDimensions())
        assert not result.infeasible, (scenario, bidirectional, condition)
        solved[condition] = result.dims
    for key in SOLVED_KEYS[scenario]:
        pareto = getattr(solved[Condition.PARETO], key)
        centre = getattr(solved[Condition.CENTRELINE], key)
        assert pareto <= centre + 2e-3, (key, solved)


def test_a_pinned_dimension_keeps_its_value_while_the_rest_are_solved():
    """Pin the entry road wider than the limit: only the exit road is solved, around it."""

    inputs = _pareto(scenario=Scenario.CORNER)
    free = solve_scenario(inputs, RoadDimensions())
    pins = Pins(dims=frozenset({"wa"}))
    pinned = solve_scenario(inputs, RoadDimensions(wa=3.5), pins=pins)
    assert not pinned.infeasible
    assert pinned.dims.wa == 3.5
    assert pinned.solved_keys == ("wb",)
    assert pinned.solved
    assert pinned.pins == pins
    assert pinned.min_clearance >= inputs.threshold - 1e-3
    assert free.dims.wa < 3.5, "固定值要比极限宽，才谈得上让出空间"
    assert pinned.dims.wb <= free.dims.wb + 2e-3, "进入道更宽，驶出道不必更宽"


def test_a_pinned_offset_is_held_where_the_operator_put_it():
    inputs = _pareto(scenario=Scenario.CORNER)
    pins = Pins(offsets=frozenset({"ea"}))
    result = solve_scenario(inputs, RoadDimensions(), Offsets(ea=0.2), pins)
    assert not result.infeasible
    assert result.offsets.ea == 0.2
    assert result.pins == pins
    assert result.solved_keys == SOLVED_KEYS[Scenario.CORNER]
    assert result.min_clearance >= inputs.threshold - 1e-3


def test_with_every_dimension_pinned_the_road_is_only_judged():
    inputs = _pareto(scenario=Scenario.CORNER)
    pins = Pins.all_dims(Scenario.CORNER)
    roomy = solve_scenario(inputs, RoadDimensions(wa=3.0, wb=3.0), pins=pins)
    assert roomy.solved_keys == ()
    assert not roomy.solved
    assert not roomy.infeasible
    assert (roomy.dims.wa, roomy.dims.wb) == (3.0, 3.0)
    assert roomy.status is ClearanceStatus.SAFE
    assert roomy.min_clearance >= inputs.threshold
    tight = solve_scenario(inputs, RoadDimensions(wa=2.0, wb=2.0), pins=pins)
    assert tight.solved_keys == ()
    assert (tight.dims.wa, tight.dims.wb) == (2.0, 2.0)
    assert tight.status is ClearanceStatus.OUTSIDE
    assert tight.min_clearance < 0


def test_the_centreline_condition_ignores_pins_and_offsets():
    """Nothing can be pinned on the centreline; whatever is passed in must change nothing."""

    inputs = _inputs(scenario=Scenario.CORNER)
    plain = solve_scenario(inputs, RoadDimensions())
    noisy = solve_scenario(
        inputs,
        RoadDimensions(),
        Offsets(ea=0.3, eb=-0.2),
        Pins(dims=frozenset({"wa"}), offsets=frozenset({"ea"})),
    )
    assert noisy.dims == plain.dims
    assert noisy.offsets == plain.offsets == CENTRED
    assert noisy.pins == NO_PINS
    assert noisy.solved_keys == plain.solved_keys == SOLVED_KEYS[Scenario.CORNER]
    assert noisy.min_clearance == plain.min_clearance


def test_a_pinned_lateral_offset_lifts_the_centreline_cap():
    """The cap rests on the truck being free to stay on the centreline; pin it off and

    the centreline road is no longer feasible, so the cap cannot apply. Pushing the entry
    leg 0.9 m the wrong way has to come out as a road wider than the centreline answer, and
    still a feasible one.
    """

    centre = solve_scenario(_inputs(scenario=Scenario.CORNER), RoadDimensions())
    inputs = _pareto(scenario=Scenario.CORNER)
    pushed = solve_scenario(
        inputs, RoadDimensions(), Offsets(ea=-0.9), Pins(offsets=frozenset({"ea"}))
    )
    assert not pushed.infeasible
    assert pushed.offsets.ea == -0.9
    assert pushed.dims.wa > centre.dims.wa + 0.1, (pushed.dims, centre.dims)
    assert pushed.min_clearance >= inputs.threshold - 1e-3


def test_pinning_a_shared_leg_in_a_two_way_layout_changes_nothing():
    """A two-way corner holds the branch at zero whatever ``eb`` says, so pinning it is moot."""

    inputs = _pareto(scenario=Scenario.CORNER, bidirectional=True)
    plain = solve_scenario(inputs, RoadDimensions())
    pinned = solve_scenario(
        inputs, RoadDimensions(), Offsets(eb=0.5), Pins(offsets=frozenset({"eb"}))
    )
    assert pinned.dims == plain.dims
    assert pinned.offsets.ea == plain.offsets.ea
    assert pinned.min_clearance == plain.min_clearance


def test_a_pinned_aisle_that_cannot_hold_the_radius_still_names_the_width_it_needs():
    """Pinning only the aisle width fixes the pitch, so the fit is known before any search.

    Without the early check the search for the head depth fails and the generic no-answer
    is reported, losing the one number the operator can act on.
    """

    inputs = _pareto(scenario=Scenario.UTURN, radius=1.60)
    result = solve_scenario(
        inputs, RoadDimensions(w=1.80, b=0.60), pins=Pins(dims=frozenset({"w"}))
    )
    assert result.infeasible
    # The free aisle offsets lean outwards first, so the answer is under 2R - b = 2.6.
    assert result.required_lane_width is not None
    assert 1.80 < result.required_lane_width < 2.6
    assert 0 < result.radius_shortfall < 0.4
    assert result.solved_keys == ()


def test_the_search_path_slopes_inside_a_breach_instead_of_reading_flat_zero():
    """A body across a wall with its centre inside must not read 0.0 on the search path.

    Flat means the offset descent never moves; the corner depth gives it a slope.
    """

    inputs = _pareto(scenario=Scenario.CORNER)
    dims = RoadDimensions(wa=3.0, wb=2.2)
    at_centre = evaluate(inputs, dims, Offsets(), COARSE).clearance
    nearer = evaluate(inputs, dims, Offsets(ea=0.2, eb=0.15), COARSE).clearance
    assert at_centre < 0.0
    assert nearer > at_centre


def test_a_fully_pinned_road_that_fits_with_offsets_is_not_judged_outside():
    """Regression: the descent used to sit at (0, 0) on the flat plateau and report OUTSIDE."""

    result = solve_scenario(
        _pareto(scenario=Scenario.CORNER),
        RoadDimensions(wa=3.0, wb=2.2),
        pins=Pins.all_dims(Scenario.CORNER),
    )
    assert result.status is ClearanceStatus.SAFE, result.min_clearance
    assert result.offsets.ea > 0.2 and result.offsets.eb > 0.1


def test_pinning_a_dimension_still_drives_the_rest_to_a_real_limit():
    """With the trunk pinned at 3.0 m the branch must come out well under the plateau answer."""

    result = solve_scenario(
        _pareto(scenario=Scenario.CORNER),
        RoadDimensions(wa=3.0),
        pins=Pins(dims=frozenset({"wa"})),
    )
    assert result.solved_keys == ("wb",)
    assert result.dims.wb < 2.25, result.dims
    assert result.min_clearance >= result.inputs.threshold - 1e-3


def test_a_solved_result_never_reports_below_the_threshold():
    """The search and the report must agree on the basin: 'solved' means it fits."""

    result = solve_scenario(
        _pareto(scenario=Scenario.CROSSBACK),
        RoadDimensions(ls=1.0, wv=3.0),
        pins=Pins(dims=frozenset({"ls", "wv"})),
    )
    assert result.solved
    assert result.status is ClearanceStatus.SAFE
    assert result.min_clearance >= result.inputs.threshold - 1e-3


@pytest.mark.parametrize("bidirectional", [False, True])
def test_free_aisle_offsets_can_widen_a_uturn_that_is_too_tight_on_the_centreline(
    bidirectional,
):
    """(w + b) / 2 < R on the centreline, yet leaning outwards makes the circle fit."""

    inputs = _pareto(
        scenario=Scenario.UTURN,
        bidirectional=bidirectional,
        dimensions=VehicleDimensions(width=1.0, center_front=1.0, center_rear=0.5),
        radius=1.5,
        threshold=0.10,
    )
    result = solve_scenario(
        inputs, RoadDimensions(w=2.5, b=0.3), pins=Pins(dims=frozenset({"w"}))
    )
    assert not result.infeasible
    assert result.solved_keys == ("d",)
    assert result.layout.turn_radius is not None and result.layout.turn_radius >= 1.5 - 1e-9
    assert result.min_clearance >= 0.10 - 1e-3


def test_the_required_aisle_width_accounts_for_the_offsets_leaning_outwards():
    """With the aisle offsets free the aisle can be narrower than ``2R - b``."""

    inputs = _pareto(scenario=Scenario.UTURN, radius=1.60)
    free = solve_scenario(
        inputs, RoadDimensions(w=1.80, b=0.60), pins=Pins(dims=frozenset({"w"}))
    )
    centred = solve_scenario(
        inputs,
        RoadDimensions(w=1.80, b=0.60),
        pins=Pins(dims=frozenset({"w"}), offsets=frozenset({"e1", "e2"})),
    )
    assert free.infeasible and centred.infeasible
    assert centred.required_lane_width == pytest.approx(2.6)
    assert free.required_lane_width is not None
    assert 1.80 < free.required_lane_width < 2.6
    # Buildable is not the same as feasible: at that width the circle fits with the
    # aisle offsets leaning outwards, whether or not the walls then leave the threshold.
    trial = RoadDimensions(w=free.required_lane_width + 0.01, b=0.60)
    pins = Pins(dims=frozenset({"w"}))
    leaning = Offsets(
        **{spec.key: spec.low for spec in offset_specs(inputs, trial, pins) if spec.key != "yc"}
    )
    assert build_layout(inputs, trial, leaning).buildable
    assert not build_layout(inputs, trial, Offsets()).buildable


def test_an_infeasible_result_under_pins_names_the_pins_as_the_cause():
    result = solve_scenario(
        _pareto(scenario=Scenario.CORNER),
        RoadDimensions(),
        Offsets(ea=5.0),
        Pins(offsets=frozenset({"ea"})),
    )
    assert result.infeasible
    assert "固定" in result.bottleneck
    assert result.pins.offsets == frozenset({"ea"})


def test_an_offset_pinned_past_the_road_edge_is_reported_not_refused():
    result = solve_scenario(
        _pareto(scenario=Scenario.CORNER),
        RoadDimensions(wa=3.0, wb=3.0),
        Offsets(ea=1.4),
        Pins.all_dims(Scenario.CORNER).with_offset("ea", True),
    )
    assert result.offsets.ea == pytest.approx(1.4)
    assert result.status is ClearanceStatus.OUTSIDE
    assert result.min_clearance < 0


def test_the_centreline_cap_still_applies_when_only_a_dimension_is_pinned():
    """Pinning a dimension keeps the truck free to sit on the centreline, so the cap holds."""

    inputs = _pareto(scenario=Scenario.CORNER)
    pins = Pins(dims=frozenset({"wa"}))
    pareto = solve_scenario(inputs, RoadDimensions(wa=3.4), pins=pins)
    centre = solve_scenario(
        replace(inputs, condition=Condition.CENTRELINE), RoadDimensions(wa=3.4)
    )
    assert pareto.solved_keys == ("wb",)
    assert pareto.dims.wb <= centre.dims.wb + 1e-6


def test_checking_the_solved_road_or_a_wider_one_never_reads_worse_than_the_solve():
    """The full-pinned check of the numbers the solve just reported must agree with it.

    The axis-by-axis descent used to stop a few centimetres short on the ridge between
    the two coupled offsets, so a road 1 cm wider than the solved one could read warning.
    """

    inputs = _pareto(scenario=Scenario.CORNER)
    solved = solve_scenario(inputs, RoadDimensions(wb=2.2), pins=Pins(dims=frozenset({"wb"})))
    assert solved.status is ClearanceStatus.SAFE
    for extra in (0.0, 0.01, 0.03, 0.06):
        checked = solve_scenario(
            inputs,
            RoadDimensions(wa=solved.dims.wa + extra, wb=2.2),
            pins=Pins.all_dims(Scenario.CORNER),
        )
        assert checked.status is ClearanceStatus.SAFE, (extra, checked.min_clearance)
        assert checked.min_clearance >= solved.min_clearance - 0.01


@pytest.mark.parametrize("width", [2.8, 3.0])
def test_a_two_way_uturn_with_the_aisle_pinned_still_meets_the_threshold(width):
    """Two ways this used to read 'solved' yet below threshold with the aisle pinned.

    At 3.0 m the Pareto descent never found the narrow feasible pocket of the arc start
    the centreline road relies on; at 2.8 m the centreline cap itself fell short because
    the guard closed the coarse over-read too slowly.
    """

    inputs = _pareto(scenario=Scenario.UTURN, bidirectional=True)
    result = solve_scenario(inputs, RoadDimensions(w=width), pins=Pins(dims=frozenset({"w"})))
    assert result.solved_keys == ("d",)
    assert result.status is ClearanceStatus.SAFE, result.min_clearance
    assert result.min_clearance >= inputs.threshold - 1e-3
    assert result.centred_clearance is not None
    assert result.min_clearance >= result.centred_clearance - 1e-6


def test_feasible_bands_cover_a_pinned_offset_too():
    """A pinned leg still gets a band: it tells the operator how far it could be moved."""

    inputs = _pareto(scenario=Scenario.CORNER)
    result = solve_scenario(
        inputs, RoadDimensions(), Offsets(ea=0.2), Pins(offsets=frozenset({"ea"}))
    )
    assert result.min_clearance >= inputs.threshold - 1e-3, "固定值本身可行"
    bands = {band.key: band for band in result.bands}
    assert set(bands) == {"ea", "eb"}
    assert not bands["ea"].empty
    assert bands["ea"].low - 1e-9 <= 0.2 <= bands["ea"].high + 1e-9, bands["ea"]
    direct = {
        band.key: band for band in feasible_bands(inputs, result.dims, result.offsets)
    }
    assert direct == bands


def test_stubback_starts_inside_the_branch_and_leaves_along_the_trunk():
    """The maneuver the requirement owner settled on, pinned end to end.

    Nose south inside the branch, one quarter turn in reverse onto the east side of the
    trunk, then forward away west. The shape it replaced never left the trunk at all: both
    of its arcs met on the trunk centreline, so the front axle bottomed out one radius down
    and only the tail ever swung into the branch.
    """

    inputs = _inputs(scenario=Scenario.STUBBACK)
    result = solve_scenario(inputs, RoadDimensions())
    primitives = result.layout.maneuvers[0].primitives
    assert [item.gear for item in primitives] == [Gear.REVERSE, Gear.DRIVE]

    samples = sample_poses(primitives, DIMENSIONS, FINE)
    reach = np.where(samples.gear_is_drive, DIMENSIONS.center_front, -DIMENSIONS.center_front)
    nose_x, nose_y = samples.x + reach * samples.ux, samples.y + reach * samples.uy

    branch_floor = -result.dims.wh / 2 - result.dims.ls
    assert nose_y[0] < -result.dims.wh / 2, "起点车头必须已经在支路里"
    assert nose_y[0] == pytest.approx(samples.y[0] - DIMENSIONS.center_front, abs=1e-6)
    assert nose_y[0] > branch_floor, "车头不能穿出支路尽头"
    assert samples.x[0] == pytest.approx(0.0, abs=1e-6), "起点落在支路中线上"

    assert samples.x[-1] < samples.x[0], "驶出方向朝西"
    assert samples.y[-1] == pytest.approx(0.0, abs=1e-6), "终点回到主路中线"
    assert nose_x[-1] < samples.x[-1], "终点车头朝西"
    assert bool(samples.gear_is_drive[-1])

    turned = max(samples.x[: len(samples) // 2])
    assert turned > 0, "倒车转弯经过主路东侧"


def test_the_stub_branch_runs_on_and_its_depth_is_not_a_dimension():
    """A stub road carries on past the parked truck, so how much deeper is nobody's limit.

    It used to be solved for, back when the maneuver turned around inside the branch. The
    truck now only starts there, and its nose reaching further in costs nothing.
    """

    assert "ls" not in SOLVED_KEYS[Scenario.STUBBACK]
    result = solve_scenario(_inputs(scenario=Scenario.STUBBACK), RoadDimensions())
    floor = min(point[1] for point in result.layout.region)
    nose = result.layout.maneuvers[0].primitives[0]
    start_y = nose.centre[1] + nose.radius * math.sin(nose.start_angle)
    assert floor < start_y - DIMENSIONS.center_front - 2.0, "支路尽头必须远到够不着"


def test_the_trunk_reach_matches_the_closed_form_and_survives_the_mirror():
    """出弯主路深度 = R + 中心后距 - 支路宽/2 + 阈值, measured from the far wall of the mouth.

    The widest reverse pose is the one where the wheels come straight: the body is then
    along the trunk with its tail a full 中心后距 past the turn centre. Two-way mirrors that
    maneuver, so the reading must not change -- and it cannot be walled in and searched for,
    because the mirrored maneuver drives away through the side the other one swings into.
    """

    for bidirectional in (False, True):
        inputs = _inputs(scenario=Scenario.STUBBACK, bidirectional=bidirectional)
        result = solve_scenario(inputs, RoadDimensions())
        assert result.trunk_reach is not None
        expected = (
            inputs.radius
            + DIMENSIONS.center_rear
            - result.dims.wv / 2
            + inputs.threshold
        )
        assert result.trunk_reach == pytest.approx(expected, abs=2e-3), bidirectional

    other = solve_scenario(_inputs(scenario=Scenario.CORNER), RoadDimensions())
    assert other.trunk_reach is None, "只有借支路那个场景有这项"
